saefportal/datasets/urls.py
from django.urls import path

from . import views

app_name = "datasets"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DatasetDetailView.as_view(), name='dataset_detail'),
    path('search/', views.SearchDatasetsListView.as_view(), name='search_datasets'),
    path('create_connection/', views.ConnectionCreateView.as_view(), name='create_connection'),
    path('update_connection/<int:pk>/', views.ConnectionUpdateView.as_view(), name='update_connection'),
    path('delete_connection/<int:pk>/', views.ConnectionDeleteView.as_view(), name='delete_connection'),
    path('create_query_dataset/', views.QueryDatasetCreateView.as_view(), name='create_query_dataset'),
    path('update_dataset/<int:pk>/', views.DatasetUpdateView.as_view(), name='update_dataset'),
    path('import_datasets/', views.ImportDatasetsCreateView.as_view(), name='import_datasets'),
    path('upload_datasets/', views.UploadDatasetsCreateView.as_view(), name='upload_datasets'),
    path('delete_dataset/<int:pk>/', views.DatasetDeleteView.as_view(), name='delete_dataset'),
    path('profile_history/<int:pk>/', views.ReadProfileHistory.as_view(), name='profile_history'),
    path('ajax/test_connection/', views.test_connection, name='test_connection'),
    path('ajax/update_datastore_form/', views.update_datastore_form, name='update_datastore_form'),
    path('ajax/query_preview/', views.query_preview, name='query_preview'),
    path('ajax/connection_datasets/', views.connection_datasets, name='connection_datasets'),
    path('ajax/update_profile_history/', views.update_read_profile_history, name='update_profile_history'),
    path('ajax/create_note/', views.create_note, name='create_note'),
    path('ajax/delete_note/<int:dataset_id>/<int:note_id>/', views.delete_note, name='delete_note'),
]

saefportal/home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

saefportal/jobs/urls.py
from django.urls import path

from . import views

app_name = "jobs"
urlpatterns = [
    path('', views.JobListView.as_view(), name='index'),
    path('delete/<int:pk>/', views.JobDeleteView.as_view(), name='delete'),
    path('create/', views.JobCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.JobUpdateView.as_view(), name='update'),
    path('run_history/<int:pk>/', views.RunHistoryReadView.as_view(), name='run_history'),
    path('trigger/<int:pk>/', views.TriggerJobView.as_view(), name='trigger'),
    path('ajax/update_task_form/', views.update_task_form, name='update_task_form')
]

saefportal/saefportal/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path
import notifications.urls

from util.dropbox_util import save_dropbox_token
from util.google_util import save_google_token
from util.one_drive_util import save_one_drive_token

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('', include('saef.urls'), name='saef'),
    path('settings/', include('settings.urls'), name='settings'),
    path('jobs/', include('jobs.urls'), name='jobs'),
    path('manage/', include('datasets.urls'), name='manage'),
    path('restapi/', include('restapi.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('saveOneDriveToken/', save_one_drive_token, name='save_one_drive_token'),
    path('saveGoogleToken/', save_google_token, name='save_google_token'),
    path('saveDropboxToken/', save_dropbox_token, name='save_dropbox_token'),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saefportal/jobs/models.py
import uuid

from cron_descriptor import get_description
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_celery_beat.models import PeriodicTask
from simple_history.models import HistoricalRecords

from saef.mixins import SaveWithoutHistoricalRecordMixin
from users.models import User


class Job(models.Model, SaveWithoutHistoricalRecordMixin):
    class TemplateTask(models.TextChoices):
        PROFILE_DATASET = "PROFILE_DATASET", _("Profile dataset")
        REFRESH_DATA = "REFRESH_DATA", _("Refresh data")
        EXTRACT_METADATA = "EXTRACT_METADATA", _("Extract metadata")

    name = models.CharField(max_length=128)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.CharField(max_length=1024, blank=True, default="")
    template_task = models.CharField(max_length=64, choices=TemplateTask.choices)

    alert_on_start_email = models.CharField("On start", max_length=500, blank=True, null=True)
    alert_on_success_email = models.CharField("On success", max_length=500, blank=True, null=True)
    alert_on_failure_email = models.CharField("On failure", max_length=500, blank=True, null=True)

    history = HistoricalRecords(excluded_fields=["owner", "description", "template_task", "alert_on_start_email",
                                                 "alert_on_success_email", "alert_on_failure_email"])

    def __str__(self):
        return self.name

    def get_task(self):
        """Return a three-tuple with the format (task_type, task, task_label)."""
        return "template", self.template_task, self.TemplateTask[self.template_task].label

    def get_readable_cron(self):
        """If the job is scheduled, return the cron syntax and a human readable version of the cron syntax."""
        periodic_task = self.get_periodic_task()
        if periodic_task:
            crontab_lst = str(periodic_task.crontab).split(" ")
            crontab = " ".join(crontab_lst[:len(crontab_lst)-2])

            return crontab, get_description(crontab)
        else:
            return "", "Manual"

    def get_periodic_task(self):
        try:
            return PeriodicTask.objects.get(name=self.id)
        except PeriodicTask.DoesNotExist:
            return None

    def has_email_alerts(self):
        return (self.alert_on_start_email or self.alert_on_success_email or self.alert_on_failure_email) is not None

    def get_last_job_run(self):
        job_history = JobRun.objects.filter(job=self).order_by("-start_datetime")
        if job_history:
            return job_history[0]
        else:
            return None

    def get_job_run_history(self):
        job_history = JobRun.objects.filter(job=self).order_by("-start_datetime")
        if job_history:
            return job_history
        else:
            return None


class JobRun(models.Model):
    class Status(models.TextChoices):
        SUCCEEDED = "SUCCEEDED", _("Succeeded")
        SUCCEEDED_ISSUE = "SUCCEEDED_ISSUE", _("Succeeded with issue")
        FAILED = "FAILED", _("Failed")
        RUNNING = "RUNNING", _("Running")

    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name="job_runs")
    start_datetime = models.DateTimeField("Run Start Time", auto_now_add=True)
    end_datetime = models.DateTimeField("Run End Time", blank=True, null=True)
    execution_id = models.UUIDField(editable=False, default=uuid.uuid4)

    status = models.CharField(max_length=64, choices=Status.choices, default=Status.RUNNING)
    result = models.JSONField(blank=True, null=True)
    parameters = models.JSONField(blank=True, null=True)

    def get_status_icon(self):
        if self.status == self.Status.SUCCEEDED:
            return '<i class="fas fa-check-circle success-green"></i>'
        elif self.status == self.Status.SUCCEEDED_ISSUE:
            return '<i class="fas fa-check-circle success-with-issue-yellow"></i>'
        elif self.status == self.Status.RUNNING:
            return '<i class="fas fa-sync-alt"></i>'
        else:
            return '<i class="fas fa-exclamation-circle warning-red"></i>'

saefportal/datasets/views/connection_views.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView

import datastores.forms
from datasets.forms import CreateConnectionModelForm, UpdateConnectionModelForm
from datasets.models import Connection
from datasets.util import create_database_datastore, group_connection_types, connect_to_datastore
from settings.mixins import DatalakeRequiredMixin
from users.mixins import ObjectPermissionRequiredMixin


@method_decorator(login_required, name="dispatch")
class ConnectionCreateView(DatalakeRequiredMixin, BSModalCreateView):
    form_class = CreateConnectionModelForm
    template_name = "datasets/connection/create_connection.html"
    success_url = reverse_lazy("datasets:index")

    def get_context_data(self, **kwargs):
        context = super(ConnectionCreateView, self).get_context_data(**kwargs)
        context["grouped_connection_types"] = group_connection_types()

        return context

    def form_valid(self, form):
        # Bootstrap modal forms POSTs twice, one ajax POST for form validation and another for saving.
        if not self.request.is_ajax():
            return connect_to_datastore(self.request, form)

        return HttpResponseRedirect(self.success_url)


@method_decorator(login_required, name="dispatch")
class ConnectionUpdateView(ObjectPermissionRequiredMixin, BSModalUpdateView):
    model = Connection
    form_class = UpdateConnectionModelForm
    success_url = reverse_lazy("datasets:index")
    template_name = "datasets/connection/update_connection.html"
    success_message = "Success: Connection was updated."
    object_permission = "update_connection"


@method_decorator(login_required, name="dispatch")
class ConnectionDeleteView(ObjectPermissionRequiredMixin, DeleteView):
    model = Connection
    success_url = reverse_lazy("datasets:index")
    success_message = "Connection was deleted."
    object_permission = "delete_connection"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        datastore = self.get_object().datastore
        if datastore:
            datastore.delete()

        messages.success(self.request, self.success_message)

        return super(ConnectionDeleteView, self).delete(request, *args, **kwargs)


@login_required
def test_connection(request):
    """Validate that the given connection works using a temporary datastore."""
    datastore = create_database_datastore(request.POST)

    return JsonResponse({"connection_valid": datastore.is_connection_valid()})


@login_required
def update_datastore_form(request):
    """Return rendered html with a form corresponding to the requested datastore."""
    datastore_type = request.GET.get("datastore_type", None)

    if datastore_type == Connection.Type.POSTGRES:
        form = datastores.forms.PostgresDatastoreModelForm()
    elif datastore_type == Connection.Type.AZURE:
        form = datastores.forms.AzureDatastoreModelForm()
    elif datastore_type == Connection.Type.GOOGLE_CLOUD_STORAGE:
        form = datastores.forms.GoogleCloudStorageDatastoreForm()
    elif datastore_type == Connection.Type.AZURE_BLOB_STORAGE or datastore_type == Connection.Type.AZURE_DATA_LAKE:
        form = datastores.forms.AzureDatastoreForm()
    elif datastore_type == Connection.Type.AMAZON_S3:
        form = datastores.forms.AmazonS3DatastoreForm()
    else:
        form = datastores.forms.FileDatastoreForm()

    return render(request, "datasets/connection/datastore_form.html", {"form": form})

saefportal/datasets/views/index_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from datasets.models import Connection, Dataset
from datasets.util import get_uploaded_datasets


@login_required
def index(request):
    context = {"connections": Connection.objects.all().order_by("name"), "uploaded_datasets": get_uploaded_datasets()}

    return render(request, "datasets/index.html", context)


@method_decorator(login_required, name="dispatch")
class SearchDatasetsListView(ListView):
    model = Dataset
    template_name = "datasets/search_datasets.html"
    paginate_by = 5
    context_object_name = "search_datasets"
    ordering = ["name"]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context["connections"] = Connection.objects.all()
        context["datasets"] = Dataset.objects.all()

        return context

    def get_queryset(self):
        search_term = self.request.GET.get("q", "")

        return Dataset.objects.filter(name__icontains=search_term) | Dataset.objects.filter(tags__icontains=search_term)

saefportal/datasets/views/note_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from datasets.models import Dataset, Note


@login_required
def create_note(request):
    dataset_id = request.POST.get("dataset_id", None)
    note_text = request.POST.get("note_text", None)

    # Only create the note if the requesting user has at least view permission for the dataset.
    if request.user.has_permission("view_dataset", Dataset.objects.get(id=dataset_id)):
        Note.objects.create(dataset_id=dataset_id, text=note_text, created_by_id=request.user.id)

    return render_modified_note_content(request, dataset_id)


@login_required
@csrf_exempt
def delete_note(request, dataset_id, note_id):
    # Only delete the note if the requesting user has at least view permission for the dataset.
    if request.user.has_permission("view_dataset", Dataset.objects.get(id=dataset_id)):
        Note.objects.filter(id=note_id).delete()

    return render_modified_note_content(request, dataset_id)


def render_modified_note_content(request, dataset_id):
    """Helper function to return modified content in note modification views."""
    dataset = Dataset.objects.get(id=dataset_id)

    # Adding "ajax": True to the context to avoid collapsing the note card when modifying notes through ajax requests.
    return render(request, "datasets/dataset_detail/notes.html", {"dataset": dataset, "ajax": True})

saefportal/datasets/views/profile_history_views.py
from bootstrap_modal_forms.generic import BSModalReadView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator

from datasets.models import Dataset
from users.mixins import ObjectPermissionRequiredMixin


@method_decorator(login_required, name="dispatch")
class ReadProfileHistory(ObjectPermissionRequiredMixin, BSModalReadView):
    model = Dataset
    template_name = "datasets/dataset_detail/read_profile_history.html"
    object_permission = "view_dataset"

    def get_context_data(self, **kwargs):
        context = super(ReadProfileHistory, self).get_context_data()
        profile_runs = context["dataset"].get_profile_runs()

        if profile_runs:
            context["selected_run"] = profile_runs[0]

        return context


@login_required
def update_read_profile_history(request):
    selected_run = None
    dataset_id = request.GET.get("dataset_id", None)
    run_id = request.GET.get("run_id", None)

    dataset = Dataset.objects.get(id=dataset_id)

    # Only return information on the selected run if the requesting user has at least view permission for the dataset.
    if request.user.has_permission("view_dataset", dataset):
        selected_run = dataset.get_profile_runs().get(id=run_id)

    return render(request, "datasets/dataset_detail/read_profile_history.html",
                  {"dataset": dataset, "selected_run": selected_run})

saefportal/datasets/templates/datasets/dataset_detail/dataset_detail.html
{% extends "datasets/index.html" %}

{% load static %}

{% block content %}
    <script type="text/javascript" src="{% static "datasets/js/degree_of_change_chart.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static "datasets/css/dataset_detail/dataset_detail.css" %}">

    <div class="card mt-3" id="dataset-detail">

        <div class="card-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-auto">
                        <h2>{{ dataset.get_type_icon|safe }} {{ dataset.title }}</h2>
                    </div>

                    <div class="col-auto dataset-key">
                        Key: <span id="dataset-key">{{ dataset.key }}</span>
                        <i class="fas fa-copy" id="copy-dataset-key" data-clipboard-target="#dataset-key"
                           data-bs-toggle="tooltip" data-placement="auto" title="Copied!" data-bs-trigger="click"></i>
                    </div>

                    <div class="float-right">
                        {% if dataset.id in user.get_grouped_permission_ids.dataset.level_2 %}
                            <a href="{% url 'datasets:delete_dataset' dataset.id %}"
                               onclick="return confirm('Are you sure?');">
                                <i class="fas fa-trash delete-dataset warning-red-hover"></i>
                            </a>
                        {% else %}
                            <i class="fas fa-trash delete-dataset warning-red-hover"
                               id="request-delete-dataset"></i>
                        {% endif %}
                        <i class="fas fa-cog update-dataset general-blue-hover" id="update-dataset"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-body dataset-detail">

            <table class="table dataset-detail">
                <tbody>
                <tr>
                    <th scope="row" style="width: 13%" class="text-right">Name:</th>
                    <td>{{ dataset.name }}</td>
                </tr>
                <tr>
                    <th scope="row" style="width: 13%" class="text-right">Owner:</th>
                    <td>{{ dataset.owner }}</td>
                </tr>
                {% if dataset.query %}
                    <tr>
                        <th scope="row" class="text-right">Query:</th>
                        <td id="query">{{ dataset.query }}</td>
                    </tr>
                {% elif dataset.table %}
                    <tr>
                        <th scope="row" class="text-right">Table:</th>
                        <td>{{ dataset.table }}</td>
                    </tr>
                {% endif %}
                <tr id="dataset-description">
                    <th scope="row" class="text-right">Description:</th>
                    <td>{{ dataset.description }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Type:</th>
                    <td>{{ dataset.get_connection_type_display }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Tags:</th>
                    <td>{{ dataset.tags }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Status:</th>
                    <td>{{ dataset.get_status|safe }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Contacts:</th>
                    <td>{{ dataset.contacts.all|join:", " }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Connection details:</th>
                    <td>
                        <i class="fas fa-eye show-connection-string" id="connection-string-button"></i>
                        <span data-value="{{ dataset.get_connection_details }}" data-visible="false"
                              id="connection-string"></span>
                    </td>
                </tr>
                </tbody>
            </table>

            <div class="accordion" id="dataset-accordion">
                <div class="card" id="definition">
                    {% include "datasets/dataset_detail/definition.html" %}
                </div>

                <div class="card" id="profile">
                    {% include "datasets/dataset_detail/profile.html" %}
                </div>

                <div class="card" id="linked-jobs">
                    {% include "datasets/dataset_detail/linked_jobs.html" %}
                </div>

                <div class="card" id="notes">
                    {% include "datasets/dataset_detail/notes.html" %}
                </div>
            </div>

        </div>
    </div>

    <script>
        $(document).ready(function () {
            $("#update-dataset").modalForm({
                formURL: "{% url 'datasets:update_dataset' dataset.id %}"
            });

            $("#request-delete-dataset").modalForm({
                formURL: "{% url 'request_access' 'dataset' dataset.id 2 %}"
            });
        });

        var $connectionString = $("#connection-string")

        // Initially hide the connection string and show it if attached button is clicked.
        $connectionString.html("&#9679;".repeat(40))

        $("#connection-string-button").click(function () {
            if ($connectionString.attr("data-visible") === "true") {
                $connectionString.html("&#9679;".repeat(40))
                $connectionString.attr("data-visible", false)
            } else {
                $connectionString.html($connectionString.attr("data-value"))
                $connectionString.attr("data-visible", true)
            }
        })

        // Set up "copy to clipboard" icon for copying the dataset key.
        var copyDatasetKey = new Clipboard("#copy-dataset-key");
        copyDatasetKey.on('success', (event) => {
            event.clearSelection();
        });

        // Set up tooltip for when the dataset key is copied.
        var $copyDatasetKey = $("#copy-dataset-key")
        var tooltip = new bootstrap.Tooltip($copyDatasetKey)

        // Manually hiding tooltip after 2 second delay.
        $copyDatasetKey.on("show.bs.tooltip", function () {
            setTimeout(function () {
                $copyDatasetKey.tooltip("hide")
            }, 2000)
        })
    </script>
{% endblock content %}

saefportal/datasets/templates/datasets/dataset_detail/notes.html
<div class="accordion-item">
    <h2 class="accordion-header" id="notes-heading">
        <button class="accordion-button {% if not ajax %}collapsed{% endif %}" type="button" data-bs-toggle="collapse"
                data-bs-target="#notes-collapse"
                aria-expanded="true" aria-controls="notes-collapse">
            Notes <span class="badge rounded-pill bg-dark">{{ dataset.get_notes|length }}</span>
        </button>
    </h2>
    <div id="notes-collapse" class="accordion-collapse collapse {% if ajax %}show{% endif %}"
         aria-labelledby="notes-heading">
        <div class="accordion-body dataset-detail">

            <table class="table row-border" id="notes-table">
                <thead>
                <tr>
                    <th>Note</th>
                    <th>Created by</th>
                    <th>Created at</th>
                    <th id="notes-action"></th>
                </tr>
                </thead>
                <tbody>
                {% for note in dataset.get_notes %}
                    <tr>
                        <td>{{ note.text }}</td>
                        <td>{{ note.created_by }}</td>
                        <td>{{ note.updated_at }}</td>
                        <td><i class="fas fa-trash delete-note warning-red-hover" data-id="{{ note.id }}"></i></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="container float-start" id="create-note-container">
                <div class="row">
                    <div class="col-auto">
                        <input type="text" class="form-control" placeholder="New note" id="new-note-text"/>
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-success" id="create-note" type="button">Add note</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('#notes-table').DataTable({
            columnDefs: [
                {orderable: false, targets: 3}
            ],
            order: [[2, 'desc']],
            lengthChange: false,
            info: false,
            searching: false,
            pageLength: 5,
        });

        $("th:contains('Note')").css("width", "800px")
        $("th:contains('Created by')").css("width", "80px")
        $("th:contains('Created at')").css("width", "120px")
    });

    var $noteTextArea = $("#new-note-text")
    $noteTextArea.val("")

    // Creating and deleting notes using ajax requests to avoid page reloads. This is done specifically
    // for notes due to the intended simple process of working with the object.

    // Create a new note when the save button is clicked.
    $("#create-note").on("click", function () {
        var noteText = $noteTextArea.val()

        if (noteText !== "") {
            $.ajax({
                type: "POST",
                url: "{% url 'datasets:create_note' %}",
                data: {
                    "dataset_id": "{{ dataset.id }}",
                    "note_text": noteText,
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                },
                success: function (result) {
                    $("#notes").html(result)
                }
            });
        }
    })

    // Delete all selected notes when the "Delete selected" button is clicked.
    $(".delete-note").on("click", function () {
        var noteId = $(this).attr("data-id")

        $.ajax({
            type: "DELETE",
            url: "{% url 'datasets:delete_note' dataset_id=dataset.id note_id=0 %}".replace("/0/", `/${noteId}/`),
            success: function (result) {
                $("#notes").html(result)
            }
        });
    })
</script>

saefportal/datasets/templates/datasets/dataset_detail/profile.html
<div class="accordion-item">
    <h2 class="accordion-header" id="profile-heading">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#profile-collapse"
                aria-expanded="true" aria-controls="profile-collapse">
            Profile
        </button>
    </h2>
    <div id="profile-collapse" class="accordion-collapse collapse" aria-labelledby="profile-heading">
        <div class="accordion-body dataset-detail">

            {% with dataset.get_profile_runs as profile_runs %}
                {% if profile_runs %}
                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-auto profile info" style="width: 25%">
                                <table class="table text-nowrap" id="general-profile-info">
                                    <tr>
                                        <th scope="row" style="width: 12%" class="text-right">Number of profiles:
                                        </th>
                                        <td>{{ profile_runs|length }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row" style="width: 12%" class="text-right">First profile:</th>
                                        <td>{{ profile_runs.last.start_datetime }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row" style="width: 12%" class="text-right">Latest profile:</th>
                                        <td>{{ profile_runs.0.start_datetime }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row" style="width: 12%" class="text-right">Latest status:</th>
                                        <td>{{ profile_runs.0.get_status_display }}</td>
                                    </tr>
                                </table>
                            </div>

                            <div class="col-auto" style="width: 70%">
                                <div class="card">
                                    <canvas id="profile-canvas"></canvas>
                                    <button type="button" class="btn btn-outline-primary btn-sm reset-chart"
                                            id="reset-chart-btn">
                                        Reset
                                    </button>
                                </div>
                            </div>

                            <div class="col-auto">
                                <i class="fas fa-expand-arrows-alt expand-profile general-blue-hover"
                                   id="read-profile-history"></i>
                            </div>

                        </div>
                    </div>
                {% else %}
                    No profile runs are available.
                {% endif %}
            {% endwith %}

            <div class="modal fade" tabindex="-1" role="dialog" id="profile-history-modal" data-bs-backdrop="static">
                <div class="modal-dialog modal-xl" role="document">
                    <div class="modal-content" id="profile-history-modal-content"></div>
                </div>
            </div>

        </div>
    </div>
</div>


<script>
    if ($("#profile-canvas").length) {
        var chartData = JSON.parse("{{ dataset.get_degree_of_change_data|safe }}".replaceAll("'", "\""))
        var chart = degreeOfChangeChart($("#profile-canvas")[0], chartData)

        $("#reset-chart-btn").on("click", function () {
            chart.resetZoom()
        })
    }

    // Connect the "expand" icon with the modal that shows the profile history.
    $(document).ready(function () {
        $("#read-profile-history").modalForm({
            modalID: "#profile-history-modal",
            formURL: "{% url 'datasets:profile_history' dataset.id %}"
        });
    });
</script>