saefportal/home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

saefportal/saefportal/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path
import notifications.urls

from util.dropbox_util import save_dropbox_token
from util.google_util import save_google_token
from util.one_drive_util import save_one_drive_token

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('', include('saef.urls'), name='saef'),
    path('settings/', include('settings.urls'), name='settings'),
    path('jobs/', include('jobs.urls'), name='jobs'),
    path('manage/', include('datasets.urls'), name='manage'),
    path('restapi/', include('restapi.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('saveOneDriveToken/', save_one_drive_token, name='save_one_drive_token'),
    path('saveGoogleToken/', save_google_token, name='save_google_token'),
    path('saveDropboxToken/', save_dropbox_token, name='save_dropbox_token'),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saefportal/settings/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = "settings"
urlpatterns = [
    path('<int:pk>/', views.SettingsUpdateView.as_view(), name='settings'),
    path('create_datalake_connection/', views.DatalakeConnectionCreateView.as_view(),
         name="create_datalake_connection"),
    path('create_datalake_connection/<str:redirect>/', views.DatalakeConnectionCreateView.as_view(),
         name="create_datalake_connection"),
    path('update_datalake_connection/', views.DatalakeConnectionUpdateView.as_view(),
         name="update_datalake_connection"),
    path('delete_datalake_connection/<int:pk>/', views.DatalakeConnectionDeleteView.as_view(),
         name='delete_datalake_connection'),
    path('ajax/update_datalake_form/', views.update_datalake_form, name="update_datalake_form"),
    path('ajax/add_contact/', views.add_contact, name='add_contact'),
    path('ajax/delete_contact/<int:contact_id>/', views.delete_contact, name='delete_contact')
]

urlpatterns += staticfiles_urlpatterns()

saefportal/settings/models.py
import pytz

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from solo.models import SingletonModel


class Contact(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField(max_length=256)

    def __str__(self):
        return self.name


class Settings(SingletonModel):
    timezone = models.CharField(max_length=100, choices=[(tz, tz) for tz in pytz.common_timezones], default="UTC")

    datalake_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, blank=True, null=True)
    datalake_id = models.PositiveIntegerField(blank=True, null=True)
    datalake = GenericForeignKey("datalake_type", "datalake_id")

    dataset_refresh_frequency = models.CharField(max_length=10, blank=True, null=True)
    delete_outdated_frequency = models.CharField(max_length=10, blank=True, null=True)
    # The threshold is specified in minutes.
    delete_outdated_threshold = models.PositiveIntegerField(blank=True, null=True)
    try_live_connection = models.BooleanField(default=False)

    profile_expected_datasets_n = models.IntegerField(default=10)
    profile_failed_threshold = models.FloatField(default=0.5)
    profile_delta_deviation = models.FloatField(default=0.2)

    email_host_user = models.CharField(max_length=100, default="")
    email_host_password = models.CharField(max_length=100, default="")
    email_host = models.CharField(max_length=50, default="localhost")
    email_port = models.IntegerField(default=587)
    email_use_tls = models.BooleanField(default=True)

    class Meta:
        verbose_name = "settings"

saefportal/settings/forms.py
from bootstrap_modal_forms.forms import BSModalForm
from django import forms

from settings.models import Settings
from users.models import UserProfile


class SettingsModelForm(forms.ModelForm):
    class Meta:
        model = Settings
        fields = ["timezone", "dataset_refresh_frequency", "delete_outdated_frequency", "delete_outdated_threshold",
                  "try_live_connection", "profile_expected_datasets_n", "profile_failed_threshold",
                  "profile_delta_deviation", "email_host_user", "email_host_password", "email_host", "email_port",
                  "email_use_tls"]
        widgets = {
            "timezone": forms.Select(attrs={'class': "selectpicker"}),
            "profile_expected_datasets_n": forms.NumberInput(attrs={"min": "1"}),
            "profile_failed_threshold": forms.NumberInput(attrs={"min": "0", "max": "1", "step": "0.05"}),
            "profile_delta_deviation": forms.NumberInput(attrs={"min": "0", "max": "1", "step": "0.05"}),
            "email_host_password": forms.PasswordInput(render_value=True),
            "delete_outdated_threshold": forms.NumberInput(attrs={"min": "0"})
        }
        labels = {
            "profile_expected_datasets_n": "Number of datasets for expected",
            "profile_failed_threshold": "Degree of change fail threshold",
            "profile_delta_deviation": "Expected dataset deviation scale",
            "email_host_user": "Host user",
            "email_host_password": "Host password",
            "email_host": "Host",
            "email_port": "Port",
            "email_use_tls": "Use TLS"
        }

    def get_profile_task_fields(self):
        return [self["profile_failed_threshold"], self["profile_expected_datasets_n"], self["profile_delta_deviation"]]

    def get_grouped_email_fields(self):
        return [[self["email_host_user"], self["email_host_password"]], [self["email_host"], self["email_port"]]]


class UserProfileModelForm(forms.ModelForm):
    email = forms.CharField(max_length=100)

    class Meta:
        model = UserProfile
        fields = ["first_name", "last_name", "phone"]

    def get_grouped_fields(self):
        """Grouping fields for easier handling in the template."""
        return [[self["first_name"], self["last_name"]], [self["email"], self["phone"]]]


class DatalakeConnectionModelForm(BSModalForm):
    """Empty form used since Django Bootstrap Modal Forms requires a form."""
    pass

saefportal/datasets/views/connection_views.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView

import datastores.forms
from datasets.forms import CreateConnectionModelForm, UpdateConnectionModelForm
from datasets.models import Connection
from datasets.util import create_database_datastore, group_connection_types, connect_to_datastore
from settings.mixins import DatalakeRequiredMixin
from users.mixins import ObjectPermissionRequiredMixin


@method_decorator(login_required, name="dispatch")
class ConnectionCreateView(DatalakeRequiredMixin, BSModalCreateView):
    form_class = CreateConnectionModelForm
    template_name = "datasets/connection/create_connection.html"
    success_url = reverse_lazy("datasets:index")

    def get_context_data(self, **kwargs):
        context = super(ConnectionCreateView, self).get_context_data(**kwargs)
        context["grouped_connection_types"] = group_connection_types()

        return context

    def form_valid(self, form):
        # Bootstrap modal forms POSTs twice, one ajax POST for form validation and another for saving.
        if not self.request.is_ajax():
            return connect_to_datastore(self.request, form)

        return HttpResponseRedirect(self.success_url)


@method_decorator(login_required, name="dispatch")
class ConnectionUpdateView(ObjectPermissionRequiredMixin, BSModalUpdateView):
    model = Connection
    form_class = UpdateConnectionModelForm
    success_url = reverse_lazy("datasets:index")
    template_name = "datasets/connection/update_connection.html"
    success_message = "Success: Connection was updated."
    object_permission = "update_connection"


@method_decorator(login_required, name="dispatch")
class ConnectionDeleteView(ObjectPermissionRequiredMixin, DeleteView):
    model = Connection
    success_url = reverse_lazy("datasets:index")
    success_message = "Connection was deleted."
    object_permission = "delete_connection"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        datastore = self.get_object().datastore
        if datastore:
            datastore.delete()

        messages.success(self.request, self.success_message)

        return super(ConnectionDeleteView, self).delete(request, *args, **kwargs)


@login_required
def test_connection(request):
    """Validate that the given connection works using a temporary datastore."""
    datastore = create_database_datastore(request.POST)

    return JsonResponse({"connection_valid": datastore.is_connection_valid()})


@login_required
def update_datastore_form(request):
    """Return rendered html with a form corresponding to the requested datastore."""
    datastore_type = request.GET.get("datastore_type", None)

    if datastore_type == Connection.Type.POSTGRES:
        form = datastores.forms.PostgresDatastoreModelForm()
    elif datastore_type == Connection.Type.AZURE:
        form = datastores.forms.AzureDatastoreModelForm()
    elif datastore_type == Connection.Type.GOOGLE_CLOUD_STORAGE:
        form = datastores.forms.GoogleCloudStorageDatastoreForm()
    elif datastore_type == Connection.Type.AZURE_BLOB_STORAGE or datastore_type == Connection.Type.AZURE_DATA_LAKE:
        form = datastores.forms.AzureDatastoreForm()
    elif datastore_type == Connection.Type.AMAZON_S3:
        form = datastores.forms.AmazonS3DatastoreForm()
    else:
        form = datastores.forms.FileDatastoreForm()

    return render(request, "datasets/connection/datastore_form.html", {"form": form})

saefportal/settings/views.py
from bootstrap_modal_forms.generic import BSModalFormView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import model_to_dict
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import UpdateView, DeleteView

from datalakes.forms import (GoogleCloudStorageDatalakeForm, FileStoreDatalakeForm, AzureDatalakeForm,
                             AmazonS3DatalakeForm)
from settings.forms import SettingsModelForm, UserProfileModelForm, DatalakeConnectionModelForm
from settings.models import Settings, Contact
from settings.util import modify_refresh_all_task, modify_delete_outdated_task, connect_to_datalake, \
    group_datalake_types
from users.mixins import AdminPermissionRequiredMixin
from users.models import UserProfile, User


@method_decorator(login_required, name="dispatch")
class SettingsUpdateView(SuccessMessageMixin, UpdateView):
    model = Settings
    template_name = "settings/settings.html"
    form_class = SettingsModelForm
    success_url = reverse_lazy("settings:settings", kwargs={"pk": 1})
    success_message = "Settings were updated."

    def get_context_data(self, **kwargs):
        context = super(SettingsUpdateView, self).get_context_data(**kwargs)

        initial_user_profile_data = model_to_dict(UserProfile.objects.get(user=self.request.user))
        initial_user_profile_data["email"] = User.objects.get(pk=self.request.user.pk).email
        context["user_profile_form"] = UserProfileModelForm(initial_user_profile_data)
        context["contacts"] = Contact.objects.all().order_by("name")

        context["datalake_type"] = str(self.object.datalake_type)

        return context

    def form_valid(self, form):
        # Saving the fields specified in the settings form.
        self.object = form.save()

        # Saving the fields specified in the user profile form.
        user_profile_data = {k: self.request.POST[k] for k in ["first_name", "last_name", "phone"]}
        UserProfile.objects.filter(user=self.request.user).update(**user_profile_data)

        User.objects.filter(pk=self.request.user.pk).update(email=self.request.POST["email"])

        modify_refresh_all_task(self.object, self.request)
        modify_delete_outdated_task(self.object, self.request)

        self.object.save()
        messages.success(self.request, self.success_message)

        return HttpResponseRedirect(self.get_success_url())


class DatalakeConnectionCreateUpdateView(AdminPermissionRequiredMixin, BSModalFormView):
    """Base class to avoid duplicated code between create and update view."""
    form_class = DatalakeConnectionModelForm
    success_url = reverse_lazy("settings:settings", args=[1])

    def get_context_data(self, **kwargs):
        context = super(DatalakeConnectionCreateUpdateView, self).get_context_data(**kwargs)
        context["grouped_datalake_types"] = group_datalake_types()

        return context

    def form_valid(self, form):
        # Bootstrap modal forms POSTs twice, one ajax POST for form validation and another for saving.
        if not self.request.is_ajax():
            return connect_to_datalake(self.request, form)

        return HttpResponseRedirect(self.success_url)


@method_decorator(login_required, name="dispatch")
class DatalakeConnectionCreateView(DatalakeConnectionCreateUpdateView):
    template_name = "settings/datalake/create_datalake_connection.html"


@method_decorator(login_required, name="dispatch")
class DatalakeConnectionUpdateView(DatalakeConnectionCreateUpdateView):
    template_name = "settings/datalake/update_datalake_connection.html"


@method_decorator(login_required, name="dispatch")
class DatalakeConnectionDeleteView(AdminPermissionRequiredMixin, DeleteView):
    success_message = "Datalake connection was deleted."

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        Settings.objects.get().datalake.delete()

        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(reverse_lazy("settings:settings", args=[1]))


@login_required
def add_contact(request):
    name = request.POST.get("name", None)
    email = request.POST.get("email", None)

    Contact.objects.create(name=name, email=email)

    return render(request, "settings/contacts.html", {"contacts": Contact.objects.all().order_by("name")})


@login_required
@csrf_exempt
def delete_contact(request, contact_id):
    Contact.objects.filter(id=contact_id).delete()

    return render(request, "settings/contacts.html", {"contacts": Contact.objects.all().order_by("name")})


@login_required
def update_datalake_form(request):
    """Return rendered html with a form corresponding to the requested datalake."""
    datalake_type = request.GET.get("datalake_type", None)

    if datalake_type == "GOOGLE_CLOUD_STORAGE":
        form = GoogleCloudStorageDatalakeForm()
    elif datalake_type == "AZURE_BLOB_STORAGE" or datalake_type == "AZURE_DATA_LAKE":
        form = AzureDatalakeForm()
    elif datalake_type == "AMAZON_S3":
        form = AmazonS3DatalakeForm()
    else:
        form = FileStoreDatalakeForm()

    return render(request, "settings/datalake/datalake_form.html", {"datalake_form": form})

saefportal/settings/templates/settings/connection.html
{% load static %}

<h5>Datalake</h5>
{% with user.user_profile.settings.datalake as datalake %}
    {% if not datalake %}
        {% if user.is_staff or "Admin" in user.get_group_names %}
            <button type="button" class="btn btn-primary" id="connect-datalake">Connect to datalake</button>
        {% endif %}
    {% else %}
        {% if datalake_type == "one drive datalake" %}
            <img src="{% static 'settings/images/OneDrive-logo.svg' %}" style="height: 50px" class="pe-2">
        {% elif datalake_type == "google drive datalake" %}
            <img src="{% static 'settings/images/Google_Drive_icon.svg' %}" style="height: 45px" class="pe-2">
        {% elif datalake_type == "dropbox datalake" %}
            <img src="{% static 'settings/images/Dropbox_Icon.svg' %}" style="height: 50px">
        {% elif datalake_type == "google cloud storage datalake" %}
            <img src="{% static 'settings/images/Google_Cloud_Storage_icon.svg' %}" style="height: 50px" class="pe-2">
        {% elif datalake_type == 'azure blob storage datalake' %}
            <img src="{% static 'settings/images/azure-storage-blob.svg' %}" style="height: 50px" class="pe-2">
        {% elif datalake_type == 'azure data lake datalake' %}
            <img src="{% static 'settings/images/azure-data-lake.svg' %}" style="height: 50px" class="pe-2">
        {% elif datalake_type == 'amazon s3 datalake' %}
            <img src="{% static 'settings/images/amazon_s3_logo.svg' %}" style="height: 50px" class="pe-2">
        {% endif %}
        {{ datalake }}
        {% if user.is_staff or "Admin" in user.get_group_names %}
            <i class="fas fa-cog general-blue-hover" id="update-datalake" role="button"></i>
            <a onclick="return confirm('Are you sure?');"
               href="{% url 'settings:delete_datalake_connection' datalake.id %}">
                <i class="fas fa-trash warning-red-hover" id="delete-datalake-connection"></i>
            </a>
        {% endif %}
    {% endif %}
{% endwith %}

<h5>Datasets</h5>
<div class="checkbox">
    <label>
        <input type="checkbox" id="refresh-checkbox" name="refresh-checkbox">
        Refresh datasets periodically
    </label>
    <i tabindex="0" data-bs-trigger="focus" class="fas fa-info-circle" data-bs-toggle="popover"
       data-bs-content="Refresh the snapshots of all datasets in the datalake according to the below frequency."></i>
</div>

<div id="refresh-frequency-container" class="ps-4">
    <div id="refresh-cron-input" class="pb-2"></div>
</div>

<div class="checkbox">
    <label>
        <input type="checkbox" id="delete-outdated-checkbox" name="delete-outdated-checkbox">
        Delete outdated snapshots periodically
    </label>
    <i tabindex="0" data-bs-trigger="focus" class="fas fa-info-circle" data-bs-toggle="popover"
       data-bs-content="Delete snapshots older than the below threshold according to the below frequency.
       The newest snapshot is never deleted."></i>
</div>

<div id="delete-outdated-container" class="ps-4">
    Older than <input type="number" id="days" class="threshold" min="0"> days
    <input type="number" id="hours" class="threshold" max="23" min="0"> hours
    <input type="number" id="minutes" class="threshold" max="59" min="0"> minutes
    <div id="delete-outdated-cron-input" class="pb-2"></div>
</div>

<div class="form-check">
    {{ form.try_live_connection }}
    <label id="try-live-connection" for={{ form.try_live_connection.id_for_label }} class="m-0">
        {{ form.try_live_connection.label }}
    </label>
    <i tabindex="0" data-bs-trigger="focus" class="fas fa-info-circle" data-bs-toggle="popover"
       data-bs-content="When using segments of the website that interact with your data, always try a live
       connection to the database first. If unchecked, SAEF uses the datalake."></i>
</div>

<!-- Hidden fields that can be changed using JQuery when cron input is changed.-->
<div style="display: none">{{ form.dataset_refresh_frequency }}</div>
<div style="display: none">{{ form.delete_outdated_frequency }}</div>

<!-- Hidden field that can be changed when the delete outdated time threshold is changed.-->
<div style="display: none">{{ form.delete_outdated_threshold }}</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal" data-bs-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#connect-datalake").modalForm({
            formURL: "{% url 'settings:create_datalake_connection' %}"
        });

        $("#update-datalake").modalForm({
            formURL: "{% url 'settings:update_datalake_connection' %}"
        });
    });

    // Set up the cron input field used to set the dataset update frequency.
    var refreshCronInput = $("#refresh-cron-input").cron({
        onChange: function () {
            $("#id_dataset_refresh_frequency").val($(this).cron("value"))
        }
    });

    // Set up the cron input field used to set the outdated delete frequency.
    var deleteOutdatedCronInput = $("#delete-outdated-cron-input").cron({
        onChange: function () {
            $("#id_delete_outdated_frequency").val($(this).cron("value"))
        }
    });

    // When the refresh datasets checkbox is changed, show or hide the relevant settings.
    $("#refresh-checkbox").on("change", function () {
        if ($(this).is(":checked")) {
            $("#refresh-frequency-container").show()
        } else {
            $("#refresh-frequency-container").hide()
        }
    })

    // When the delete outdated checkbox is changed, show or hide the relevant settings.
    $("#delete-outdated-checkbox").on("change", function () {
        if ($(this).is(":checked")) {
            $("#delete-outdated-container").show()
            $(".threshold").prop("required", true)
        } else {
            $("#delete-outdated-container").hide()
            $(".threshold").prop("required", false)
        }
    })

    // Show the dataset refresh frequency setting and update the cron input if it is set.
    if ("{{ settings.dataset_refresh_frequency }}" !== "None") {
        $("#refresh-checkbox").prop("checked", true)
        refreshCronInput.cron("value", "{{ settings.dataset_refresh_frequency }}")
    } else {
        $("#refresh-checkbox").prop("checked", false)
        $("#refresh-frequency-container").hide()
    }

    // Show the delete outdated settings, update the cron input and the threshold if it is set.
    if ("{{ settings.delete_outdated_frequency }}" !== "None") {
        $("#delete-outdated-checkbox").prop("checked", true)
        deleteOutdatedCronInput.cron("value", "{{ settings.delete_outdated_frequency }}")

        var total_minutes = "{{ settings.delete_outdated_threshold }}"
        $("#days").val(Math.floor(total_minutes / 24 / 60))
        $("#hours").val(Math.floor(total_minutes / 60 % 24))
        $("#minutes").val(total_minutes % 60)

        $(".threshold").prop("required", true)
    } else {
        $("#delete-outdated-checkbox").prop("checked", false)
        $("#delete-outdated-container").hide()
    }

    // When the delete outdated threshold days, hours or minutes are changed, convert the change into minutes.
    $(".threshold").on("change", function () {
        var minutes = $("#days").val() * 1440 + $("#hours").val() * 60 + parseInt($("#minutes").val())

        if (minutes < 0) {
            minutes = 0
        }
        $("#id_delete_outdated_threshold").val(minutes)
    })
</script>

saefportal/settings/templates/settings/contacts.html
<h5>Contacts</h5>

<label for=contact-name>Name</label>
<input type="text" id="contact-name" placeholder="Contact name">

<label for=contact-email>Email</label>
<input type="text" id="contact-email" placeholder="Contact email">

<button class="btn btn-success" id="add-contact" type="button" disabled>Add contact</button>

<table class="table contacts">
    <tbody>
    {% for contact in contacts %}
        <tr>
            <td class="contact-checkbox"><input type="checkbox" value="{{ contact.id }}"></td>
            <td>{{ contact.name }} - {{ contact.email }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<button class="btn btn-danger" id="delete-selected" type="button" disabled>Delete selected</button>

<script type="text/javascript">
    var $addContactButton = $("#add-contact")
    var $nameInput = $("#contact-name")
    var $emailInput = $("#contact-email")
    var $deleteSelectedButton = $("#delete-selected")

    // Only enable the "Add contact" button when both input fields are not empty.
    $("#contact-name, #contact-email").on("input", function () {
        if ($nameInput.val() && $emailInput.val()) {
            $addContactButton.prop("disabled", false)
        } else {
            $addContactButton.prop("disabled", true)
        }
    })

    // Make an ajax request to add the contact when the "Add contact" button is clicked.
    $addContactButton.on("click", function () {
        $.ajax({
            type: "POST",
            url: "{% url 'settings:add_contact' %}",
            data: {"name": $nameInput.val(), "email": $emailInput.val(), "csrfmiddlewaretoken": "{{ csrf_token }}"},
            success: function (result) {
                $("#list-contacts").html(result)
            }
        });
    })

    // Only enable the "Delete selected" button when at least one contact is selected.
    $(".contact-checkbox input").on("change", function () {
        if ($(this).is(":checked") || getCheckedContacts().length > 0) {
            $deleteSelectedButton.prop("disabled", false)
        } else {
            $deleteSelectedButton.prop("disabled", true)
        }
    })

    function getCheckedContacts() {
        return $(".contact-checkbox input").get().filter(checkbox => $(checkbox).is(":checked"))
    }

    // Make an ajax request to delete each selected contact when the "Delete selected" button is clicked.
    $deleteSelectedButton.on("click", function () {
        getCheckedContacts().map(input => {
            var contactId = $(input).attr("value")

            $.ajax({
                type: "DELETE",
                url: "{% url 'settings:delete_contact' contact_id=0 %}".replace("/0/", `/${contactId}/`),
                success: function (result) {
                    $("#list-contacts").html(result)
                }
            });
        })
    })

</script>

saefportal/settings/templates/settings/edit_profile.html
<h5>Profile</h5>
<div class="container user-profile">
    {% for group in user_profile_form.get_grouped_fields %}
        <div class="row">
            {% for field in group %}
                <div class="col">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>

<h5>General</h5>
<label for={{ form.timezone.id_for_label }}>{{ form.timezone.label }}</label>
{{ form.timezone }}

<script type="text/javascript">
    $(".selectpicker").selectpicker({
        liveSearch: true
    });
</script>

saefportal/settings/templates/settings/email_server.html
<h5>Email server</h5>
<div class="container email-fields">
    {% for group in form.get_grouped_email_fields %}
        <div class="row">
            {% for field in group %}
                <div class="col">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
        </div>
    {% endfor %}

    {{ form.email_use_tls }}
    <label for={{ form.email_use_tls.id_for_label }}>{{ form.email_use_tls.label }}</label>
    <i tabindex="0" data-bs-trigger="focus" class="fas fa-info-circle" data-bs-toggle="popover"
       data-bs-content="Use a TLS (secure) connection when talking to the SMTP server."></i>
</div>

saefportal/settings/templates/settings/tasks.html
<h5>Profile dataset</h5>
<div class="profile-task-fields">
    <label for={{ form.profile_expected_datasets_n.id_for_label }}>{{ form.profile_expected_datasets_n.label }}</label>
    <i tabindex="0" data-bs-trigger="focus" class="fas fa-info-circle" data-bs-toggle="popover"
       data-bs-content="How many previous profile runs to use when creating the expected dataset."></i>
    {{ form.profile_expected_datasets_n }}

    <label for={{ form.profile_failed_threshold.id_for_label }}>{{ form.profile_failed_threshold.label }}</label>
    <i tabindex="0" data-bs-trigger="focus" class="fas fa-info-circle" data-bs-toggle="popover"
       data-bs-content="If the actual degree of change is above this threshold, the profile run fails."></i>
    {{ form.profile_failed_threshold }}

    <label for={{ form.profile_delta_deviation.id_for_label }}>{{ form.profile_delta_deviation.label }}</label>
    <i tabindex="0" data-bs-trigger="focus" class="fas fa-info-circle" data-bs-toggle="popover"
       data-bs-content="Scales the expected degree of change to set a threshold. If the actual degree of change is
       above this threshold, the profile run succeeds with issues."></i>
    {{ form.profile_delta_deviation }}
</div>