saefportal/datasets/urls.py
from django.urls import path

from . import views

app_name = "datasets"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DatasetDetailView.as_view(), name='dataset_detail'),
    path('search/', views.SearchDatasetsListView.as_view(), name='search_datasets'),
    path('create_connection/', views.ConnectionCreateView.as_view(), name='create_connection'),
    path('update_connection/<int:pk>/', views.ConnectionUpdateView.as_view(), name='update_connection'),
    path('delete_connection/<int:pk>/', views.ConnectionDeleteView.as_view(), name='delete_connection'),
    path('create_query_dataset/', views.QueryDatasetCreateView.as_view(), name='create_query_dataset'),
    path('update_dataset/<int:pk>/', views.DatasetUpdateView.as_view(), name='update_dataset'),
    path('import_datasets/', views.ImportDatasetsCreateView.as_view(), name='import_datasets'),
    path('upload_datasets/', views.UploadDatasetsCreateView.as_view(), name='upload_datasets'),
    path('delete_dataset/<int:pk>/', views.DatasetDeleteView.as_view(), name='delete_dataset'),
    path('profile_history/<int:pk>/', views.ReadProfileHistory.as_view(), name='profile_history'),
    path('ajax/test_connection/', views.test_connection, name='test_connection'),
    path('ajax/update_datastore_form/', views.update_datastore_form, name='update_datastore_form'),
    path('ajax/query_preview/', views.query_preview, name='query_preview'),
    path('ajax/connection_datasets/', views.connection_datasets, name='connection_datasets'),
    path('ajax/update_profile_history/', views.update_read_profile_history, name='update_profile_history'),
    path('ajax/create_note/', views.create_note, name='create_note'),
    path('ajax/delete_note/<int:dataset_id>/<int:note_id>/', views.delete_note, name='delete_note'),
]

saefportal/home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

saefportal/saefportal/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path
import notifications.urls

from util.dropbox_util import save_dropbox_token
from util.google_util import save_google_token
from util.one_drive_util import save_one_drive_token

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('', include('saef.urls'), name='saef'),
    path('settings/', include('settings.urls'), name='settings'),
    path('jobs/', include('jobs.urls'), name='jobs'),
    path('manage/', include('datasets.urls'), name='manage'),
    path('restapi/', include('restapi.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('saveOneDriveToken/', save_one_drive_token, name='save_one_drive_token'),
    path('saveGoogleToken/', save_google_token, name='save_google_token'),
    path('saveDropboxToken/', save_dropbox_token, name='save_dropbox_token'),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saefportal/datasets/models.py
import json
import uuid
from datetime import datetime

from django.core.validators import RegexValidator
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords

from analyzer.models import ActualDatasetProfile, ExpectedDatasetProfile, ActualColumnProfile, ExpectedColumnProfile
from jobs.models import Job
from saef.mixins import SaveWithoutHistoricalRecordMixin
from settings.models import Contact
from users.models import User

filename_validator = RegexValidator(r"^[\w\-. ]+$", "Name cannot be used as a folder name in the datalake.")


class Connection(models.Model):
    class Type(models.TextChoices):
        POSTGRES = "POSTGRES", _("PostgreSQL")
        AZURE = "AZURE", _("Azure SQL")
        ONEDRIVE = "ONEDRIVE", _("OneDrive")
        GOOGLE_DRIVE = "GOOGLE_DRIVE", _("Google Drive")
        DROPBOX = "DROPBOX", _("Dropbox")
        GOOGLE_CLOUD_STORAGE = "GOOGLE_CLOUD_STORAGE", _("Google Cloud Storage")
        AZURE_BLOB_STORAGE = "AZURE_BLOB_STORAGE", _("Azure Blob Storage")
        AZURE_DATA_LAKE = "AZURE_DATA_LAKE", _("Azure Data Lake")
        AMAZON_S3 = "AMAZON_S3", _("Amazon S3")

    name = models.CharField(max_length=128, unique=True, validators=[filename_validator])
    title = models.CharField(max_length=128)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    type = models.CharField(max_length=128, choices=Type.choices)
    key = models.UUIDField(editable=False, default=uuid.uuid4)

    datastore_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, blank=True, null=True)
    datastore_id = models.PositiveIntegerField(blank=True, null=True)
    datastore = GenericForeignKey("datastore_type", "datastore_id")

    history = HistoricalRecords(excluded_fields=["owner", "type", "key", "datastore_type", "datastore_id",
                                                 "datastore", "title"])

    def save(self, *args, **kwargs):
        # If the object has not been created yet.
        if not self.pk:
            self.title = self.name

        super(Connection, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_related_datasets(self):
        """Return a dict with related datasets under the categories "TABLE", "QUERY" and "VIEW"."""
        related_datasets = Dataset.objects.filter(connection_id=self.id)

        structure = {Dataset.Type.TABLE: [], Dataset.Type.QUERY: [], Dataset.Type.VIEW: []}
        [structure[dataset.type].append(dataset) for dataset in related_datasets]

        # Order the lists alphabetically.
        for key, values in structure.items():
            structure[key] = sorted(values, key=lambda x: x.name)

        return structure


class Dataset(models.Model, SaveWithoutHistoricalRecordMixin):
    class Type(models.TextChoices):
        QUERY = "QUERY", _("Query")
        TABLE = "TABLE", _("Table")
        VIEW = "VIEW", _("View")

    name = models.CharField(max_length=128, validators=[filename_validator])
    title = models.CharField(max_length=128)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.CharField(max_length=1024, blank=True, default="")
    tags = models.CharField(max_length=1024, blank=True, default="")
    contacts = models.ManyToManyField(Contact, blank=True)

    # If null, the dataset is a manually uploaded file.
    connection = models.ForeignKey(Connection, on_delete=models.CASCADE, related_name="datasets", blank=True, null=True)

    query = models.CharField(max_length=5000, null=True, blank=True)
    table = models.CharField(max_length=500, null=True, blank=True)
    file_id = models.CharField(max_length=500, null=True, blank=True)
    type = models.CharField(max_length=128, choices=Type.choices, default=Type.QUERY)

    key = models.UUIDField(editable=False, default=uuid.uuid4)
    create_datetime = models.DateTimeField(auto_now_add=True)

    history = HistoricalRecords(excluded_fields=["description", "tags", "contacts", "connection", "query", "table",
                                                 "file_id", "type", "key", "create_datetime", "test", "owner", "title"])

    class Meta:
        constraints = [models.UniqueConstraint(fields=["name", "connection"], name="Name uniqueness")]

    def save(self, *args, **kwargs):
        # If the object has not been created yet.
        if not self.pk:
            self.title = self.name

        super(Dataset, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_status(self):
        """Return the status of the latest related dataset session."""
        latest_session = DatasetRun.objects.filter(dataset_id=self.id).order_by("start_datetime")

        if latest_session:
            from django.utils import formats
            status_datetime = formats.date_format(latest_session[0].start_datetime, "DATETIME_FORMAT")
            return f"{latest_session[0].get_status_icon()} {latest_session[0].get_status_display()}: {status_datetime}"
        else:
            return "No status."

    def get_linked_jobs(self):
        """
        Return a list of job objects that are linked to the dataset. A job is linked to a dataset if the job currently
        uses the dataset key in its parameters.
        """
        linked_jobs = []
        jobs = Job.objects.all()

        for job in jobs:
            parameters = None

            periodic_task = job.get_periodic_task()
            if periodic_task:
                parameters = json.loads(periodic_task.kwargs)["task_parameters"]
            elif job.get_last_job_run():
                parameters = job.get_last_job_run().parameters

            if parameters is not None and parameters.get("dataset_key", None) == str(self.key):
                linked_jobs.append(job)

        return linked_jobs

    def get_notes(self):
        return Note.objects.filter(dataset=self).order_by("-updated_at")

    def get_profile_runs(self):
        return DatasetRun.objects.filter(dataset=self, task_name="Profile dataset").order_by("-start_datetime")

    def get_degree_of_change_data(self):
        """Return list data points that can be used to populate a line chart."""
        data = []

        for run in self.get_profile_runs().reverse():
            if run.result and "degree_of_change" in run.result:
                timestamp = int(run.start_datetime.strftime("%s")) * 1000
                degree_of_change = run.result["degree_of_change"]

                data.append({"x": timestamp, "y": degree_of_change, "id": run.id})

        return data

    def get_type_icon(self):
        if self.type == self.Type.QUERY:
            return '<i class="fas fa-search"></i>'
        elif self.type == self.Type.TABLE:
            return '<i class="fas fa-table"></i>'
        else:
            return '<i class="fas fa-eye"></i>'

    def get_connection_type_display(self):
        return self.connection.get_type_display() if self.connection else "Upload"

    def get_connection_details(self):
        return self.connection.datastore.get_connection_details() if self.connection else "No connection details"

    def get_datalake_path(self):
        """Return the path to the dataset in the datalake. If the datasets connection has been deleted, return None."""
        try:
            connection_folder = self.connection.name if self.connection else "uploads"
        except Connection.DoesNotExist:
            return None

        return f"saef/landing/{connection_folder}/{self.name}"


class DatasetRun(models.Model):
    class Type(models.TextChoices):
        JOB = "JOB", _("Job")
        API = "API", _("API")

    class Status(models.TextChoices):
        SUCCEEDED = "SUCCEEDED", _("Succeeded")
        SUCCEEDED_ISSUE = "SUCCEEDED_ISSUE", _("Succeeded with issue")
        FAILED = "FAILED", _("Failed")
        RUNNING = "RUNNING", _("Running")

    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE, related_name="dataset_runs")
    task_name = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=Type.choices, default=Type.JOB)

    start_datetime = models.DateTimeField(auto_now_add=True)
    end_datetime = models.DateTimeField(blank=True, null=True)
    created_by = models.CharField(max_length=100, default="")
    execution_id = models.UUIDField(editable=False, default=uuid.uuid4)

    result = models.JSONField(blank=True, null=True)
    status = models.CharField(max_length=128, choices=Status.choices, default=Status.RUNNING)

    def get_status_icon(self):
        if self.status == self.Status.SUCCEEDED:
            return '<i class="fas fa-check-circle success-green"></i>'
        elif self.status == self.Status.SUCCEEDED_ISSUE:
            return '<i class="fas fa-check-circle success-with-issue-yellow"></i>'
        elif self.status == self.Status.RUNNING:
            return '<i class="fas fa-sync-alt"></i>'
        else:
            return '<i class="fas fa-exclamation-circle warning-red"></i>'

    def get_actual_expected_dataset_profile(self):
        """Return dict with actual and expected data from the analyzers dataset profiles."""
        actual_dataset_profile = ActualDatasetProfile.objects.get(dataset_run=self)
        expected_dataset_profile = ExpectedDatasetProfile.objects.get(actual_dataset_profile=actual_dataset_profile)

        actual_expected_info = {}

        for key in ["row_count", "column_count", "hash_sum"]:
            actual_expected_info[key] = {"actual": getattr(actual_dataset_profile, key),
                                         "expected": getattr(expected_dataset_profile, key)}

        return actual_expected_info

    def get_actual_expected_column_profiles(self):

saefportal/datasets/views/connection_views.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView

import datastores.forms
from datasets.forms import CreateConnectionModelForm, UpdateConnectionModelForm
from datasets.models import Connection
from datasets.util import create_database_datastore, group_connection_types, connect_to_datastore
from settings.mixins import DatalakeRequiredMixin
from users.mixins import ObjectPermissionRequiredMixin


@method_decorator(login_required, name="dispatch")
class ConnectionCreateView(DatalakeRequiredMixin, BSModalCreateView):
    form_class = CreateConnectionModelForm
    template_name = "datasets/connection/create_connection.html"
    success_url = reverse_lazy("datasets:index")

    def get_context_data(self, **kwargs):
        context = super(ConnectionCreateView, self).get_context_data(**kwargs)
        context["grouped_connection_types"] = group_connection_types()

        return context

    def form_valid(self, form):
        # Bootstrap modal forms POSTs twice, one ajax POST for form validation and another for saving.
        if not self.request.is_ajax():
            return connect_to_datastore(self.request, form)

        return HttpResponseRedirect(self.success_url)


@method_decorator(login_required, name="dispatch")
class ConnectionUpdateView(ObjectPermissionRequiredMixin, BSModalUpdateView):
    model = Connection
    form_class = UpdateConnectionModelForm
    success_url = reverse_lazy("datasets:index")
    template_name = "datasets/connection/update_connection.html"
    success_message = "Success: Connection was updated."
    object_permission = "update_connection"


@method_decorator(login_required, name="dispatch")
class ConnectionDeleteView(ObjectPermissionRequiredMixin, DeleteView):
    model = Connection
    success_url = reverse_lazy("datasets:index")
    success_message = "Connection was deleted."
    object_permission = "delete_connection"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        datastore = self.get_object().datastore
        if datastore:
            datastore.delete()

        messages.success(self.request, self.success_message)

        return super(ConnectionDeleteView, self).delete(request, *args, **kwargs)


@login_required
def test_connection(request):
    """Validate that the given connection works using a temporary datastore."""
    datastore = create_database_datastore(request.POST)

    return JsonResponse({"connection_valid": datastore.is_connection_valid()})


@login_required
def update_datastore_form(request):
    """Return rendered html with a form corresponding to the requested datastore."""
    datastore_type = request.GET.get("datastore_type", None)

    if datastore_type == Connection.Type.POSTGRES:
        form = datastores.forms.PostgresDatastoreModelForm()
    elif datastore_type == Connection.Type.AZURE:
        form = datastores.forms.AzureDatastoreModelForm()
    elif datastore_type == Connection.Type.GOOGLE_CLOUD_STORAGE:
        form = datastores.forms.GoogleCloudStorageDatastoreForm()
    elif datastore_type == Connection.Type.AZURE_BLOB_STORAGE or datastore_type == Connection.Type.AZURE_DATA_LAKE:
        form = datastores.forms.AzureDatastoreForm()
    elif datastore_type == Connection.Type.AMAZON_S3:
        form = datastores.forms.AmazonS3DatastoreForm()
    else:
        form = datastores.forms.FileDatastoreForm()

    return render(request, "datasets/connection/datastore_form.html", {"form": form})

saefportal/datasets/templates/datasets/dataset/create_query_dataset.html
{% extends "datasets/dataset/create_update_dataset_base.html" %}

{% block title %}Create new query dataset{% endblock title %}
{% block submit %}Create{% endblock submit %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'datasets/css/dataset/create_update_query_dataset.css' %}">
{% endblock static %}

{% block extra_fields %}
    <div class="row mt-3">
        <div class="col">
            <label for="{{ form.connection.id_for_label }}">{{ form.connection.label }}</label>
            {{ form.connection }}
        </div>
        <div class="col">
            <div id="dataset-select-container">
                {% include "datasets/dataset/dataset_select.html" with select_multiple=False %}
            </div>
        </div>
    </div>

    {# Invisible field used to record the file id of the currently selected dataset shown in the query.#}
    {{ form.file_id }}
{% endblock extra_fields %}

{% block collapse %}
    <div class="collapse" id="query-collapse">
        <label for="{{ form.query.id_for_label }}">{{ form.query.label }}</label>
        {{ form.query }}

        <button type="button" class="btn btn-primary form-control" id="test-query">
            Test query
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="display: none"
                  id="test-query-spinner"></span>
        </button>

        <div class="collapse" id="query-result-collapse">
            {% include "datasets/dataset/query_result.html" %}
        </div>
    </div>
{% endblock collapse %}

{% block javascript %}
    <script type="text/javascript">
        // If the connection is already set due to a validation error, reset the connection select and query input.
        if ($("#id_connection").val()) {
            $("#id_connection").val("")
            $("#id_query").val("")
        }

        // Set the default owner to the current user.
        $("#id_owner").val("{{ user.id }}")

        $("#dataset-select").prop('disabled', true);
        $("#dataset-select").selectpicker('refresh');

        // When a connection is selected, show the text input for queries and the button to test the query.
        $("#{{ form.connection.id_for_label }}").on("change", function () {
            var selectedConnection = this.value

            if (selectedConnection) {
                $("#query-collapse").collapse("show")
            } else {
                $("#query-collapse").collapse("hide")
            }
        })

        // When the "Test query" button is clicked, make an ajax request to retrieve the data, populate the table and show.
        $("#test-query").on("click", function () {
            $("#test-query-spinner").show()
            $("#test-query").removeClass("is-valid").removeClass("is-invalid")

            var connectionId = $("#{{ form.connection.id_for_label }}").val()
            var query = $("#id_query").val()

            // If it is a file datastore, replace the path in the query with the ID that can be used to get the file.
            var selectedDataset = $("#dataset-select").val()
            if (selectedDataset.startsWith("Files.")) {
                var datasetInfo = JSON.parse(selectedDataset.replace("Files.", ""))
                query = query.replace(`\`${datasetInfo["name"]}\``, `\`${datasetInfo["id"]}\``)
            }

            $.ajax({
                type: "POST",
                url: "{% url 'datasets:query_preview' %}",
                data: {"connection_id": connectionId, "query": query, "csrfmiddlewaretoken": "{{ csrf_token }}"},
                success: function (result) {
                    $("#query-result-collapse").html(result)
                    $("#query-result-collapse").collapse("show")
                    $("#test-query-spinner").hide()
                }
            });
        })
    </script>
{% endblock javascript %}

saefportal/datasets/templates/datasets/dataset/create_update_dataset_base.html
{% block static %}{% endblock static %}

<form method="post" action="" id="dataset-form" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title">{% block title %}{% endblock title %}</h5>
    </div>

    <div class="modal-body">
        <div class="container">
            {% for group in form.get_grouped_fields %}
                <div class="row mb-2">
                    {% for field in group %}
                        <div class="col">
                            <div class="form-group{% if field.errors %} invalid{% endif %}">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                {% for error in field.errors %}
                                    <p class="help-block">{{ error }}</p>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}

            {% block extra_fields %}{% endblock extra_fields %}
        </div>

        {% block collapse %}{% endblock collapse %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
        <button class="btn btn-primary" type="submit" id="dataset-submit">
            {% block submit %}{% endblock submit %}
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" id="submit-spinner" style="display: none"></span>
        </button>
    </div>
</form>

<script type="text/javascript">
    $("#id_connection").addClass("form-select")

    $(".selectpicker").selectpicker({
        liveSearch: true
    });

    // When the form is submitted, show the spinner.
    $("#dataset-form").on("submit", function() {
        $("#submit-spinner").show()
    })
</script>

{% block javascript %}{% endblock javascript %}

saefportal/datasets/templates/datasets/dataset/dataset_select.html
<label for="table-select" class="d-block">
    Datasets
    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="display: none"
          id="datasets-spinner"></span>
</label>
<select class="selectpicker d-block" id="dataset-select" name="dataset-select" required
        {% if select_multiple == "True" %}multiple{% endif %}>
    {% if select_multiple == "False" %}
        <option value="" selected disabled>Nothing selected</option>
    {% endif %}
    {% for type, grouped_datasets in connection_datasets.items %}
        {% for group, datasets in grouped_datasets.items %}
            <optgroup label="{{ group }} {% if type == 'Tables' or type == 'Views' %}({{ type }}){% endif %}">
                {% for dataset in datasets %}
                    <option value="{{ type }}.{{ dataset.value }}">{{ dataset.display }}</option>
                {% endfor %}
            </optgroup>
        {% endfor %}
    {% endfor %}
</select>

<script type="text/javascript">
    $(".selectpicker").selectpicker({
        liveSearch: true
    });

    // When a connection is selected, make an ajax request to retrieve the tables and views and populate the select.
    $("#id_connection").on("change", function () {
        // Disable select while data is being retrieved.
        $("#dataset-select").prop('disabled', true);
        $("#dataset-select").selectpicker('refresh');

        var connectionId = $("#id_connection").val()

        if (connectionId) {
            $("#datasets-spinner").show()

            $.ajax({
                type: "GET",
                url: "{% url 'datasets:connection_datasets' %}",
                data: {"connection_id": connectionId, "select_multiple": "{{ select_multiple }}"},
                success: function (result) {
                    // Turn off the current event listener to avoid doubling future requests.
                    $("#id_connection").off("change")

                    $("#dataset-select-container").html(result)
                }
            });
        }
    })

    // When a dataset is selected, autofill the query input with a basic SQL query using the dataset and set the file id.
    if ($(".modal-title").text() === "Create new query dataset") {
        $("#dataset-select").on("changed.bs.select", function () {
            var dataset;
            var splitCharacter = this.value.indexOf(".")
            var split_dataset = [this.value.slice(0, splitCharacter), this.value.slice(splitCharacter + 1)]

            if (split_dataset[0] === "Tables" || split_dataset[0] === "Views") {
                dataset = split_dataset.slice(1, 3).join(".")
                $("#id_query").val(`SELECT * FROM ${dataset}`)
                $("#id_file_id").val(null)
            } else {
                dataset = JSON.parse(split_dataset[1])
                $("#id_query").val(`SELECT * FROM \`${dataset["name"]}\``)
                $("#id_file_id").val(dataset["id"])
            }
        });
    }
</script>

saefportal/datasets/templates/datasets/dataset/import_datasets.html
{% extends "datasets/dataset/create_update_dataset_base.html" %}

{% block title %}Import datasets{% endblock title %}
{% block submit %}Import{% endblock submit %}

{% block extra_fields %}
    <div class="row mt-3">
        <div class="col">
            <label for="{{ form.connection.id_for_label }}">{{ form.connection.label }}</label>
            {{ form.connection }}
        </div>
        <div class="col">
            <div id="dataset-select-container">
                {% include "datasets/dataset/dataset_select.html" with select_multiple=True %}
            </div>
        </div>
    </div>
{% endblock extra_fields %}

{% block javascript %}
    <script type="text/javascript">
        // Set the default owner to the current user.
        $("#id_owner").val("{{ user.id }}")

        $("#dataset-select").prop('disabled', true);
        $("#dataset-select").selectpicker('refresh');
    </script>
{% endblock javascript %}

saefportal/datasets/templates/datasets/dataset/query_result.html
{% if query_valid %}
    <h5>Query preview <small>(first {{ data_preview|length }} rows)</small></h5>
    <div class="query-result-container">
        <table class="table row-border text-nowrap compact" id="query-result-table">
            <thead>
            <tr>
                {% for column_name in column_names %}
                    <th>{{ column_name }}</th>
                {% endfor %}
            </tr>
            </thead>

            <tbody>
            {% for row in data_preview %}
                <tr>
                    {% for cell in row %}
                        <td>{{ cell }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

<script>
    $(document).ready(function () {
        $("#query-result-table").DataTable({
            lengthChange: false,
            paging: false,
            searching: false,
            info: false
        });
    });

    // Visually show on the "Test query" button whether the query is valid or not.
    if ("{{ query_valid }}" === "True") {
        $("#test-query").addClass("is-valid")
    } else if ("{{ query_valid }}" === "False") {
        $("#test-query").addClass("is-invalid")
    }
</script>

saefportal/datasets/templates/datasets/dataset/update_dataset.html
{% extends "datasets/dataset/create_update_dataset_base.html" %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'datasets/css/dataset/update_dataset.css' %}">
{% endblock static %}

{% block title %}Update dataset{% endblock title %}
{% block submit %}Update{% endblock submit %}

saefportal/datasets/templates/datasets/dataset/upload_datasets.html
{% extends "datasets/dataset/create_update_dataset_base.html" %}

{% block title %}Upload datasets{% endblock title %}
{% block submit %}Upload{% endblock submit %}

{% block extra_fields %}
    <label class="btn btn-success mt-2">
        Add files <input type="file" name="files" multiple="" required="" id="id_files" hidden
                         accept=".csv,.parquet,.avro,.xlsx,.xls,.xlsm,.xlsb">
    </label>

    <div id="table-container" hidden>
        <table class="table mt-2 compact" id="file-table">
            <thead class="table-dark compact text-wrap">
            <tr>
                <th>Name</th>
                <th>File type</th>
                <th>File size</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
{% endblock extra_fields %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#file-table").DataTable({
                lengthChange: false,
                info: false,
                searching: false,
                dom: "ftp",
                order: [[0, "asc"]],
                pageLength: 5,
            });

            // Set the default owner to the current user.
            $("#id_owner").val("{{ user.id }}")
        });

        // When the file input is updated, refresh the datatable with the currently added files.
        $("#id_files").on("change", function () {
            var newData = [...this.files].map(function (file) {
                var index = file.name.lastIndexOf('.');
                var [file_name, file_type] = [file.name.slice(0, index), file.name.slice(index + 1)]

                return [file_name, file_type, `${Math.ceil(file.size / 1000)} KB`]
            })

            var datatable = $("#file-table").DataTable();
            datatable.clear();
            datatable.rows.add(newData);
            datatable.draw();

            $("#table-container").prop("hidden", false)
        })
    </script>
{% endblock javascript %}