saefportal/datasets/urls.py
from django.urls import path

from . import views

app_name = "datasets"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DatasetDetailView.as_view(), name='dataset_detail'),
    path('search/', views.SearchDatasetsListView.as_view(), name='search_datasets'),
    path('create_connection/', views.ConnectionCreateView.as_view(), name='create_connection'),
    path('update_connection/<int:pk>/', views.ConnectionUpdateView.as_view(), name='update_connection'),
    path('delete_connection/<int:pk>/', views.ConnectionDeleteView.as_view(), name='delete_connection'),
    path('create_query_dataset/', views.QueryDatasetCreateView.as_view(), name='create_query_dataset'),
    path('update_dataset/<int:pk>/', views.DatasetUpdateView.as_view(), name='update_dataset'),
    path('import_datasets/', views.ImportDatasetsCreateView.as_view(), name='import_datasets'),
    path('upload_datasets/', views.UploadDatasetsCreateView.as_view(), name='upload_datasets'),
    path('delete_dataset/<int:pk>/', views.DatasetDeleteView.as_view(), name='delete_dataset'),
    path('profile_history/<int:pk>/', views.ReadProfileHistory.as_view(), name='profile_history'),
    path('ajax/test_connection/', views.test_connection, name='test_connection'),
    path('ajax/update_datastore_form/', views.update_datastore_form, name='update_datastore_form'),
    path('ajax/query_preview/', views.query_preview, name='query_preview'),
    path('ajax/connection_datasets/', views.connection_datasets, name='connection_datasets'),
    path('ajax/update_profile_history/', views.update_read_profile_history, name='update_profile_history'),
    path('ajax/create_note/', views.create_note, name='create_note'),
    path('ajax/delete_note/<int:dataset_id>/<int:note_id>/', views.delete_note, name='delete_note'),
]

saefportal/home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

saefportal/saefportal/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path
import notifications.urls

from util.dropbox_util import save_dropbox_token
from util.google_util import save_google_token
from util.one_drive_util import save_one_drive_token

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('', include('saef.urls'), name='saef'),
    path('settings/', include('settings.urls'), name='settings'),
    path('jobs/', include('jobs.urls'), name='jobs'),
    path('manage/', include('datasets.urls'), name='manage'),
    path('restapi/', include('restapi.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('saveOneDriveToken/', save_one_drive_token, name='save_one_drive_token'),
    path('saveGoogleToken/', save_google_token, name='save_google_token'),
    path('saveDropboxToken/', save_dropbox_token, name='save_dropbox_token'),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saefportal/datasets/views/connection_views.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView

import datastores.forms
from datasets.forms import CreateConnectionModelForm, UpdateConnectionModelForm
from datasets.models import Connection
from datasets.util import create_database_datastore, group_connection_types, connect_to_datastore
from settings.mixins import DatalakeRequiredMixin
from users.mixins import ObjectPermissionRequiredMixin


@method_decorator(login_required, name="dispatch")
class ConnectionCreateView(DatalakeRequiredMixin, BSModalCreateView):
    form_class = CreateConnectionModelForm
    template_name = "datasets/connection/create_connection.html"
    success_url = reverse_lazy("datasets:index")

    def get_context_data(self, **kwargs):
        context = super(ConnectionCreateView, self).get_context_data(**kwargs)
        context["grouped_connection_types"] = group_connection_types()

        return context

    def form_valid(self, form):
        # Bootstrap modal forms POSTs twice, one ajax POST for form validation and another for saving.
        if not self.request.is_ajax():
            return connect_to_datastore(self.request, form)

        return HttpResponseRedirect(self.success_url)


@method_decorator(login_required, name="dispatch")
class ConnectionUpdateView(ObjectPermissionRequiredMixin, BSModalUpdateView):
    model = Connection
    form_class = UpdateConnectionModelForm
    success_url = reverse_lazy("datasets:index")
    template_name = "datasets/connection/update_connection.html"
    success_message = "Success: Connection was updated."
    object_permission = "update_connection"


@method_decorator(login_required, name="dispatch")
class ConnectionDeleteView(ObjectPermissionRequiredMixin, DeleteView):
    model = Connection
    success_url = reverse_lazy("datasets:index")
    success_message = "Connection was deleted."
    object_permission = "delete_connection"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        datastore = self.get_object().datastore
        if datastore:
            datastore.delete()

        messages.success(self.request, self.success_message)

        return super(ConnectionDeleteView, self).delete(request, *args, **kwargs)


@login_required
def test_connection(request):
    """Validate that the given connection works using a temporary datastore."""
    datastore = create_database_datastore(request.POST)

    return JsonResponse({"connection_valid": datastore.is_connection_valid()})


@login_required
def update_datastore_form(request):
    """Return rendered html with a form corresponding to the requested datastore."""
    datastore_type = request.GET.get("datastore_type", None)

    if datastore_type == Connection.Type.POSTGRES:
        form = datastores.forms.PostgresDatastoreModelForm()
    elif datastore_type == Connection.Type.AZURE:
        form = datastores.forms.AzureDatastoreModelForm()
    elif datastore_type == Connection.Type.GOOGLE_CLOUD_STORAGE:
        form = datastores.forms.GoogleCloudStorageDatastoreForm()
    elif datastore_type == Connection.Type.AZURE_BLOB_STORAGE or datastore_type == Connection.Type.AZURE_DATA_LAKE:
        form = datastores.forms.AzureDatastoreForm()
    elif datastore_type == Connection.Type.AMAZON_S3:
        form = datastores.forms.AmazonS3DatastoreForm()
    else:
        form = datastores.forms.FileDatastoreForm()

    return render(request, "datasets/connection/datastore_form.html", {"form": form})

saefportal/datasets/views/dataset_views.py
import os

from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, DeleteView
from pyspark.sql.utils import AnalysisException

from datalakes.util import save_upload_to_datalake
from datasets.forms import (QueryDatasetModelForm, ImportDatasetsModelForm, UpdateDatasetModelForm,
                            UploadDatasetsModelForm)
from datasets.models import Connection, Dataset
from datasets.util import data_overview, import_datasets, get_uploaded_datasets, remove_existing_datasets
from settings.mixins import DatalakeRequiredMixin
from users.mixins import ObjectPermissionRequiredMixin


@method_decorator(login_required, name="dispatch")
class DatasetDetailView(ObjectPermissionRequiredMixin, DetailView):
    model = Dataset
    template_name = "datasets/dataset_detail/dataset_detail.html"
    object_permission = "view_dataset"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["connections"] = Connection.objects.all().order_by("name")
        context["uploaded_datasets"] = get_uploaded_datasets()
        context["notes"] = self.object.get_notes()

        context["data_overview_datetime"], context["column_types"], context["data_preview"] = data_overview(self.object)

        return context


@method_decorator(login_required, name="dispatch")
class QueryDatasetCreateView(DatalakeRequiredMixin, BSModalCreateView):
    template_name = "datasets/dataset/create_query_dataset.html"
    form_class = QueryDatasetModelForm

    def get_success_message(self, cleaned_data):
        return "Success: Dataset was created." if self.object.id else None

    def get_success_url(self):
        return reverse_lazy("datasets:dataset_detail", kwargs={"pk": self.object.id}) if self.object.id else ""

    def get_form_kwargs(self):
        kwargs = super(QueryDatasetCreateView, self).get_form_kwargs()
        kwargs["user"] = self.request.user

        return kwargs


@method_decorator(login_required, name="dispatch")
class ImportDatasetsCreateView(DatalakeRequiredMixin, BSModalCreateView):
    template_name = "datasets/dataset/import_datasets.html"
    form_class = ImportDatasetsModelForm
    success_message = "Datasets were imported."
    success_url = reverse_lazy("datasets:index")

    def form_valid(self, form):
        # Bootstrap modal forms POSTs twice, one ajax POST for form validation and another for saving.
        if not self.request.is_ajax():
            # Ensure the user has the correct permissions to avoid malicious users manipulating the UI to access
            # connections they are not authorized to use.
            if self.request.user.has_permission("update_connection", form.cleaned_data["connection"]):
                import_datasets(self.request.POST.getlist("dataset-select"), form)
                messages.success(self.request, self.success_message)

        return HttpResponseRedirect(reverse_lazy("datasets:index"))

    def get_form_kwargs(self):
        kwargs = super(ImportDatasetsCreateView, self).get_form_kwargs()
        kwargs["user"] = self.request.user

        return kwargs


@method_decorator(login_required, name="dispatch")
class UploadDatasetsCreateView(DatalakeRequiredMixin, BSModalCreateView):
    template_name = "datasets/dataset/upload_datasets.html"
    form_class = UploadDatasetsModelForm
    success_url = reverse_lazy("datasets:index")

    def form_valid(self, form):
        # Bootstrap modal forms POSTs twice, one ajax POST for form validation and another for saving.
        if not self.request.is_ajax():
            successful_uploads = []
            failed_uploads = []
            files = self.request.FILES.getlist("files")

            # For each uploaded file, create a dataset and save the content of the file to the datalake.
            for file in files:
                name = os.path.splitext(file.name)[0]

                # Only create a dataset if a file with the same name has not been uploaded already.
                if not Dataset.objects.filter(name=name, connection__isnull=True).exists():
                    dataset = Dataset.objects.create(name=name, owner=form.cleaned_data["owner"],
                                                     tags=form.cleaned_data["tags"], type=Dataset.Type.TABLE)
                    dataset.contacts.add(*form.cleaned_data["contacts"])

                    save_upload_to_datalake(file)
                    successful_uploads.append(file.name)
                else:
                    failed_uploads.append(file.name)

            if len(successful_uploads) > 0:
                messages.success(self.request, f"Uploaded files: {', '.join(successful_uploads)}.")

            if len(failed_uploads) > 0:
                messages.error(self.request, f"Failed to upload files: {', '.join(failed_uploads)}.")

        return HttpResponseRedirect(reverse_lazy("datasets:index"))


@method_decorator(login_required, name="dispatch")
class DatasetUpdateView(ObjectPermissionRequiredMixin, BSModalUpdateView):
    model = Dataset
    template_name = "datasets/dataset/update_dataset.html"
    form_class = UpdateDatasetModelForm
    success_message = "Success: Dataset was updated."
    object_permission = "update_dataset"

    def get_success_url(self):
        return reverse_lazy("datasets:dataset_detail", kwargs={"pk": self.object.id})


@method_decorator(login_required, name="dispatch")
class DatasetDeleteView(ObjectPermissionRequiredMixin, DeleteView):
    model = Dataset
    success_url = reverse_lazy("datasets:index")
    success_message = "Dataset was deleted."
    object_permission = "delete_dataset"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DatasetDeleteView, self).delete(request, *args, **kwargs)


@login_required
def query_preview(request):
    """Apply the query to the connection and return render with the column names and a preview of the data."""
    connection_id = request.POST.get("connection_id", None)
    query = request.POST.get("query", None)

    connection = Connection.objects.get(id=connection_id)

    # Only get the data preview if the requesting user has at least view permission for the connection.
    if request.user.has_permission("view_connection", connection):
        try:
            data_df = connection.datastore.retrieve_data(query=query, limit=10)

            column_names = list(data_df)
            data_preview = list(data_df.itertuples(index=False, name=None))

            context = {"query_valid": True, "column_names": column_names, "data_preview": data_preview}
        except (TypeError, ValueError, AnalysisException):
            context = {"query_valid": False}
    else:
        context = {"query_valid": False}

    return render(request, "datasets/dataset/query_result.html", context)


@login_required
def connection_datasets(request):
    """Return render with all possible datasets for the given connection (either tables or views)."""
    connection_id = request.GET.get("connection_id", None)
    select_multiple = request.GET.get("select_multiple", None)

    connection = Connection.objects.get(id=connection_id)

    # Ensure the user has the correct permissions to avoid malicious users manipulating the UI to access
    # connections they are not authorized to use.
    if request.user.has_permission("update_connection", connection):
        viable_datasets = connection.datastore.get_viable_datasets()

        # If select_multiple is True, the request is from the "Import datasets" modal, so we remove existing datasets.
        if select_multiple == "True":
            viable_datasets = remove_existing_datasets(viable_datasets, connection)
    else:
        viable_datasets = []

    context = {"connection_datasets": viable_datasets, "select_multiple": select_multiple}
    return render(request, "datasets/dataset/dataset_select.html", context)

saefportal/datasets/views/index_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from datasets.models import Connection, Dataset
from datasets.util import get_uploaded_datasets


@login_required
def index(request):
    context = {"connections": Connection.objects.all().order_by("name"), "uploaded_datasets": get_uploaded_datasets()}

    return render(request, "datasets/index.html", context)


@method_decorator(login_required, name="dispatch")
class SearchDatasetsListView(ListView):
    model = Dataset
    template_name = "datasets/search_datasets.html"
    paginate_by = 5
    context_object_name = "search_datasets"
    ordering = ["name"]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context["connections"] = Connection.objects.all()
        context["datasets"] = Dataset.objects.all()

        return context

    def get_queryset(self):
        search_term = self.request.GET.get("q", "")

        return Dataset.objects.filter(name__icontains=search_term) | Dataset.objects.filter(tags__icontains=search_term)

saefportal/datasets/templates/datasets/index.html
{% extends "saef/base.html" %}

{% load static %}

{% block mainsection %}
    <link rel="stylesheet" type="text/css" href="{% static "datasets/css/index.css" %}">

    <div class="container-fluid p-0">
        <div class="row m-0">

            <div class="col-auto index-sidebar mt-1">
                <div class="search-bar-container">
                    <div class="input-group rounded">
                        <input type="search" class="form-control rounded" placeholder="Search" id="search-input"/>
                        <span class="input-group-text border-0" id="search-addon">
                            <button type="submit" class="search-button" id="search-button">
                                <i class="fas fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>

                <div class="create-container mt-1">
                    <div class="dropdown">
                        <i class="fa fa-plus create general-blue-hover" data-bs-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false" data-boundary="window"></i>

                        <div class="dropdown-menu dropdown-menu-right">
                            <button class="dropdown-item" type="button" id="create-connection">Add connection</button>
                            <button class="dropdown-item" type="button" id="create-query-dataset">Add query dataset
                            </button>
                            <button class="dropdown-item" type="button" id="import-datasets">Import datasets</button>
                            <button class="dropdown-item" type="button" id="upload-datasets">Upload datasets</button>
                        </div>
                    </div>
                </div>

                {% include "datasets/index_navbar.html" %}
            </div>

            <div class="col" style="height: 100vh">
                {% block content %}
                    <div class="d-flex justify-content-center align-items-center" style="height: 100vh">
                        <div class="spinner-border" role="status" style="display: none" id="dataset-detail-spinner">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>
                {% endblock content %}
            </div>

        </div>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" id="modal" data-bs-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#create-connection").modalForm({
                formURL: "{% url 'datasets:create_connection' %}"
            });

            $("#create-query-dataset").modalForm({
                formURL: "{% url 'datasets:create_query_dataset' %}"
            });

            $("#import-datasets").modalForm({
                formURL: "{% url 'datasets:import_datasets' %}"
            });

            $("#upload-datasets").modalForm({
                formURL: "{% url 'datasets:upload_datasets' %}"
            });
        });

        // When the search button is clicked make a search request using the current content of the search bar.
        $("#search-button").on("click", function () {
            var searchInput = $("#search-input").val()

            if (searchInput) {
                document.location.href = "{% url 'datasets:search_datasets' %}" + `?q=${searchInput}`
            }
        })

        // When the enter key is pressed while the search input is focused, trigger the search.
        $("#search-input").keypress(function (event) {
            // To support multiple browsers.
            var keycode = (event.keyCode ? event.keyCode : event.which);

            if (keycode === 13) {
                $("#search-button").click()
            }
        });

        // When a dataset is clicked, record the currently open tabs in the accordion.
        $(".list-group-item").on("click", function () {
            $(".accordion-collapse.show").each(function () {
                localStorage.setItem($(this).attr("id"), $(this).attr("id"))
            })
        })

        // Reopen the tabs that are saved in local storage.
        $(".accordion-collapse").each(function () {
            if (localStorage.getItem($(this).attr("id"))) {
                $(this).addClass("show")
                localStorage.removeItem($(this).attr("id"))
            }
        })

        // When a dataset is clicked, show the spinner until the content is replaced by the dataset detail.
        $(".list-group-item.dataset-detail").on("click", function () {
            $("#dataset-detail-spinner").show()
        })
    </script>
{% endblock mainsection %}

saefportal/datasets/templates/datasets/search_datasets.html
{% extends "datasets/index.html" %}

{% load static %}
{% load bootstrap_pagination %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static "datasets/css/search_datasets.css" %}">

    <p>Showing {{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }}</p>
    {% with user.get_grouped_permission_ids as permissions %}
        {% for dataset in search_datasets %}
            <div class="card search-result">
                <div class="card-header pt-2">
                    <h3>{{ dataset.get_type_icon|safe }} {{ dataset.title }}</h3>
                </div>

                <div class="card-body text-truncate">
                    <b>Type:</b> {{ dataset.connection.get_type_display }}
                    <br>
                    {% if dataset.query %}
                        <b>Query:</b> {{ dataset.query }}
                    {% elif dataset.table %}
                        <b>Table:</b> {{ dataset.table }}
                    {% else %}
                        Uploaded dataset
                    {% endif %}
                    <br>
                    {{ dataset.description }}
                </div>

                {% if dataset.id in permissions.dataset.level_1 or dataset.id in permissions.dataset.level_2 %}
                    <a href="{% url 'datasets:dataset_detail' dataset.id %}" class="stretched-link"></a>
                {% else %}
                    <a href="#" class="stretched-link request-view-dataset"
                       data-form-url="{% url 'request_access' 'dataset' dataset.id 1 %}"></a>
                {% endif %}
            </div>
        {% endfor %}
    {% endwith %}
    {% bootstrap_paginate page_obj %}

    <script type="text/javascript">
    $(document).ready(function () {
        $(".request-view-dataset").each(function () {
            $(this).modalForm({
                formURL: $(this).data("form-url"),
            });
        });
    });
</script>
{% endblock %}